### ISSUE TITLE
--device=all not covering --device=dri as Plex Client uses Software Decoding

### ISSUE THREAD

**Issue by NightHammer1000** [flathub/tv.plex.PlexDesktop#1]
The Plex Client uses Software Decoding on the Steam Deck until you give the Flatpak the --device=dri Premission with Flatseal.
I dont think --device=all covers the Premission for DRI. It should be added on its own.

**Comment by NightHammer1000** [comment]
https://github.com/flathub/tv.plex.PlexDesktop/pull/2

**Comment by smcv** [comment]
> I dont think --device=all covers the Premission for DRI

[It does](https://github.com/flatpak/flatpak/blob/1.12.7/common/flatpak-run.c#L1564). `--device=dri` shares a subset of the devices in `/dev`; `--device=all` shares all of the devices in `/dev`, including everything that is affected by `--device=dri`.

If VA-API is not working on the Steam Deck, then the reason it's not working is likely to be something different. I've seen suggestions that something like

```
flatpak override --user --env=LIBVA_DRIVER_NAME=radeonsi tv.plex.PlexDesktop
```

might be a way to work around this, which would imply that something is going wrong in libva's auto-detection of which driver to use.

(Even if that workaround is successful, it's only valid for the Steam Deck and other devices with a `radeonsi`-compatible GPU, so it would not be appropriate to apply as a change to a Flatpak app like this one.)

**Comment by cbtlr** [comment]
Been following this issue, has it been resolved - can we launch the flatpak in gamescope mode on the steam deck or is the issue just closed?

**Comment by smcv** [comment]
The maintainers of a random Flatpak app probably don't know anything about the Steam Deck. I suggest following <https://github.com/ValveSoftware/SteamOS/issues/768>.

**Comment by cbtlr** [comment]
Follow up, it may be crashing because Plex using x11 and steam deck gaming mode is using wayland, plex for desktop client isn't setup for wayland, so it dies - which is related to an issue thread that is currently open.

**Comment by sztomi** [comment]
To be clear, this is an official flatpak maintained by Plex. There is a lot of confusion in this issue, let me try to clear it up:

  * The premise of the issue (`--device=all` not covering `--device=dri`) is incorrect. `all` does cover `dri`. That is what the "not planned" resolution
  * The Steam Deck is not currently supported (support might come in the future) - there are other reasons for it currently not working that are unrelated to --device=dri (which is again, enabled by enabling all).

>  Even the old (and from what understand non-official) Plex Flatpak worked

I don't exactly know what this refers to, but I'm guessing it's probably a Plex Media Player build that was packaged by someone. The app in this flatpak is a new client which hasn't been released to the public before. 

> plex for desktop client isn't setup for wayland

This could be one of the reasons. We are working on proper Wayland support (I have no ETA).
